[2024-04-15T09:32:32.193+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_cluster_modeling.train_model manual__2024-04-15T09:32:28.828799+00:00 [queued]>
[2024-04-15T09:32:32.204+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_cluster_modeling.train_model manual__2024-04-15T09:32:28.828799+00:00 [queued]>
[2024-04-15T09:32:32.205+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-04-15T09:32:32.245+0000] {taskinstance.py:1327} INFO - Executing <Task(BigQueryExecuteQueryOperator): train_model> on 2024-04-15 09:32:28.828799+00:00
[2024-04-15T09:32:32.258+0000] {standard_task_runner.py:57} INFO - Started process 427 to run task
[2024-04-15T09:32:32.263+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_cluster_modeling', 'train_model', 'manual__2024-04-15T09:32:28.828799+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/customer_cluster_modeling.py', '--cfg-path', '/tmp/tmpupr9h4ls']
[2024-04-15T09:32:32.266+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask train_model
[2024-04-15T09:32:32.364+0000] {task_command.py:410} INFO - Running <TaskInstance: customer_cluster_modeling.train_model manual__2024-04-15T09:32:28.828799+00:00 [running]> on host b109e2be0d92
[2024-04-15T09:32:32.564+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Tor Thanawat' AIRFLOW_CTX_DAG_ID='customer_cluster_modeling' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T09:32:28.828799+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-15T09:32:28.828799+00:00'
[2024-04-15T09:32:32.565+0000] {bigquery.py:1132} INFO - Executing: 
            CREATE OR REPLACE MODEL `mypim-410508.test1.testModelK4ClusteringaAddFeatureEng`
            OPTIONS (
                MODEL_TYPE = 'KMEANS',
                # Set the desired number of clusters here (e.g., 4)
                NUM_CLUSTERS = 4,
                # Use the recommended K-means++ initialization for better convergence
                KMEANS_INIT_METHOD = 'KMEANS++',
                # Standardize features for better distance calculations (assuming numerical data)
                STANDARDIZE_FEATURES = TRUE
            ) AS
                SELECT
                Education,
                Income,
                Kidhome,
                Teenhome,
                Recency,
                Wines,
                Fruits,
                Meat,
                Fish,
                Sweets,
                Gold,
                NumDealsPurchases,
                NumWebPurchases,
                NumCatalogPurchases,
                NumStorePurchases,
                NumWebVisitsMonth,
                Age,
                Spent,
                Living_With,
                Children,
                Family_Size,
                Is_Parent
            FROM
                `mypim-410508.test1.test_cluster`
    
[2024-04-15T09:32:32.588+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1137, in execute
    impersonation_chain=self.impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 112, in __init__
    impersonation_chain=impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 234, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 463, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `my_gcp_connection` isn't defined
[2024-04-15T09:32:32.594+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=customer_cluster_modeling, task_id=train_model, execution_date=20240415T093228, start_date=20240415T093232, end_date=20240415T093232
[2024-04-15T09:32:32.616+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 5 for task train_model (The conn_id `my_gcp_connection` isn't defined; 427)
[2024-04-15T09:32:32.635+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-04-15T09:32:32.658+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
